### ISSUE TITLE
Sagemaker is not running.

### ISSUE THREAD

**Issue by lmc19970711** [aws-deepracer-community/deepracer-for-cloud#73]
Hi, I meet the same issues as others. #71

## 1.  Some issue about the docker images.
After running `sudo ./init.sh`, it shows as follows:
```
(base) lmc@carla:~/deepracer-for-cloud/bin$ sudo ./init.sh
Detected cloud type to be local
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM nvidia/cuda:10.2-base
 ---> 55c80b56bbcd
Step 2/4 : RUN apt-get update && apt-get install -y --no-install-recommends wget python3
 ---> Using cache
 ---> f025fa6dbdf7
Step 3/4 : RUN wget https://gist.githubusercontent.com/f0k/63a664160d016a491b2cbea15913d549/raw/f25b6b38932cfa489150966ee899e5cc899bf4a6/cuda_check.py
 ---> Using cache
 ---> 4b7a643484bf
Step 4/4 : CMD ["python3","cuda_check.py"]
 ---> Using cache
 ---> 2fe7d00643dc
Successfully built 2fe7d00643dc
Successfully tagged local/gputest:latest
Please run 'aws configure --profile minio' to set the credentials
4.0.6: Pulling from awsdeepracercommunity/deepracer-rlcoach
Digest: sha256:99722292f7234f9dc57ef52904de44d960ff3d1d459ddbb3326014911f595112
Status: Image is up to date for awsdeepracercommunity/deepracer-rlcoach:4.0.6
docker.io/awsdeepracercommunity/deepracer-rlcoach:4.0.6
4.0.8-cpu-avx2: Pulling from awsdeepracercommunity/deepracer-robomaker
Digest: sha256:2eb94142bddebf4661bd7a8c570b3ba7095f2a27a918e3f97c56c5559a3ed4ea
Status: Image is up to date for awsdeepracercommunity/deepracer-robomaker:4.0.8-cpu-avx2
docker.io/awsdeepracercommunity/deepracer-robomaker:4.0.8-cpu-avx2
4.0.0-gpu: Pulling from awsdeepracercommunity/deepracer-sagemaker
Digest: sha256:867ecdd6375855e02ad1232ed8f341086109d12d806c7fa7bc930b93f4dd5297
Status: Image is up to date for awsdeepracercommunity/deepracer-sagemaker:4.0.0-gpu
docker.io/awsdeepracercommunity/deepracer-sagemaker:4.0.0-gpu
Error response from daemon: This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one.
ekuysq2js6awlqd0y80zas5g5
ekuysq2js6awlqd0y80zas5g5
Error response from daemon: rpc error: code = FailedPrecondition desc = network 6f1waq1pmy5xsvqovyvlwvtkx is in use by service 892woein99bc25wobyz4vs6b4
Error response from daemon: network with name sagemaker-local already exists

```
And I have checked the existing docker images, the images can be correctly built.
```
REPOSITORY                                  TAG              IMAGE ID       CREATED        SIZE
minio/minio                                 <none>           ecfbb387b46a   5 days ago     261MB
local/gputest                               latest           2fe7d00643dc   5 days ago     171MB
minio/minio                                 <none>           c40e60ad4853   7 days ago     259MB
hello-world                                 latest           feb5d9fea6a5   3 weeks ago    13.3kB
awsdeepracercommunity/deepracer-robomaker   4.0.8-cpu-avx2   d2ab8fd81e58   6 weeks ago    4.4GB
awsdeepracercommunity/deepracer-rlcoach     4.0.6            085ed8735130   3 months ago   757MB
nvidia/cuda                                 10.2-base        55c80b56bbcd   3 months ago   107MB
awsdeepracercommunity/deepracer-sagemaker   4.0.0-gpu        2fc6675edd10   5 months ago   3.95GB
```
Then I tried  to set my aws configure and start to train. 
## 2. `no module named boto3`
At the first time, I run the `dr-start-training`, it shows no module and I just `pip install boto3` and then after waiting for about 15 seconds, it shows`Sagemaker is not running`. Then I tried to reboot my machine and run `dr-start-training-w` again, it shows:
 ```
Wiping path s3://bucket/rl-deepracer-sagemaker.
delete: s3://bucket/rl-deepracer-sagemaker/reward_function.py
delete: s3://bucket/rl-deepracer-sagemaker/training_params.yaml
Traceback (most recent call last):
  File "/home/lmc/deepracer-for-cloud/scripts/training/prepare-config.py", line 105, in <module>
    s3_client.copy(copy_source, Bucket=s3_bucket, Key=reward_function_key)
  File "/home/lmc/anaconda3/lib/python3.8/site-packages/boto3/s3/inject.py", line 380, in copy
    return future.result()
  File "/home/lmc/anaconda3/lib/python3.8/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/home/lmc/anaconda3/lib/python3.8/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/home/lmc/anaconda3/lib/python3.8/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/home/lmc/anaconda3/lib/python3.8/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/lmc/anaconda3/lib/python3.8/site-packages/s3transfer/copies.py", line 289, in _main
    client.copy_object(
  File "/home/lmc/anaconda3/lib/python3.8/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/lmc/anaconda3/lib/python3.8/site-packages/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied.
Creating Robomaker configuration in s3://bucket/rl-deepracer-sagemaker/training_params.yaml
Updating service deepracer-0_rl_coach (id: vx09d0wayr64t9hf0ladvx12i)
Updating service deepracer-0_robomaker (id: 892woein99bc25wobyz4vs6b4)
Waiting up to 15 seconds for Sagemaker to start up...
Sagemaker is not running.

```
I guess there must be some mistake with the boto3, and I haved checked the existing containers and find the sagemaker container is not running.  And after running `dr-logs-sagemaker`, it also shows Sagemaker is not running. Please  tell me if I am wrong. Thanks!

**Comment by larsll** [comment]
No further comments from poster. Closing.

**Comment by RadioFront** [comment]
Having a similar symptom: Using latest Ubuntu under VMware Player with CPU only, 8 threads of i9-9900K, virtualize with Intel VT-x, 16GB RAM. 
Ran `cd deepracer-for-cloud && ./bin/prepare.sh`, then `bin/init.sh`. First look of `prepare.sh` did not look like preparing strange items, while it was not recommended. Maybe I need to revisit it further? Would appreciate any suggestions.

```
~/deepracer-for-cloud$ dr-start-training
[sudo] password for user: 

An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
Traceback (most recent call last):
  File "/home/user/deepracer-for-cloud/scripts/training/prepare-config.py", line 105, in <module>
    s3_client.copy(copy_source, Bucket=s3_bucket, Key=reward_function_key)
  File "/usr/lib/python3/dist-packages/boto3/s3/inject.py", line 379, in copy
    return future.result()
  File "/usr/lib/python3/dist-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/lib/python3/dist-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/usr/lib/python3/dist-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/usr/lib/python3/dist-packages/s3transfer/copies.py", line 110, in _submit
    response = call_args.source_client.head_object(
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
Creating Robomaker configuration in s3://bucketname/rl-deepracer-sagemaker/training_params.yaml
Creating service deepracer-0_rl_coach
Creating service deepracer-0_robomaker
Waiting up to 15 seconds for Sagemaker to start up...
Sagemaker is not running.
```

Sagemaker has not started, therefore there is no log for it:
```
/Desktop$ docker ps -a
CONTAINER ID   IMAGE                                                       COMMAND                  CREATED         STATUS                          PORTS      NAMES
b9c7dde67532   awsdeepracercommunity/deepracer-robomaker:4.0.12-cpu-avx2   "/bin/bash -c './run…"   2 minutes ago   Exited (0) About a minute ago              deepracer-0_robomaker.1.lrwtkrfkl5wj9iyghjy12926w
2ce26cac8182   awsdeepracercommunity/deepracer-rlcoach:4.0.12              "/bin/sh -c '(python…"   3 minutes ago   Exited (1) 2 minutes ago                   deepracer-0_rl_coach.1.lw74d3320jhg1w906u7lkpbxj
86020f1e30f7   minio/minio:latest                                          "/usr/bin/docker-ent…"   9 minutes ago   Up 9 minutes                    9000/tcp   s3_minio.1.s9lwz0pinbmrab4krrgesnwi6
```

Images are found here:
```
~/deepracer-for-cloud$ docker image ls
REPOSITORY                                  TAG                 IMAGE ID       CREATED        SIZE
minio/minio                                 <none>              be0b32759f53   2 days ago     247MB
awsdeepracercommunity/deepracer-rlcoach     4.0.12              71f57170070e   2 weeks ago    786MB
awsdeepracercommunity/deepracer-robomaker   4.0.12-cpu-avx2     4f8222317575   2 weeks ago    4.47GB
awsdeepracercommunity/deepracer-sagemaker   4.0.0-cpu-avx-mkl   9168a102a1d5   9 months ago   1.96GB
```

boto libraries are here:
```
~/Desktop$ pip list | grep boto
boto3                  1.9.253             
botocore               1.16.19         
```

system.env is here:
```
DR_CLOUD=local
DR_AWS_APP_REGION=us-east-1
DR_UPLOAD_S3_PROFILE=default
DR_UPLOAD_S3_BUCKET=aws-deepracer-assets-<hex numbers from S3/AWS>
DR_UPLOAD_S3_ROLE=to-be-defined
DR_LOCAL_S3_BUCKET=bucketname
DR_LOCAL_S3_PROFILE=default
DR_GUI_ENABLE=False
DR_KINESIS_STREAM_NAME=
DR_KINESIS_STREAM_ENABLE=True
DR_SAGEMAKER_IMAGE=4.0.0-cpu-avx-mkl
DR_ROBOMAKER_IMAGE=4.0.12-cpu-avx2
DR_ANALYSIS_IMAGE=cpu
DR_COACH_IMAGE=4.0.12
DR_WORKERS=1
DR_ROBOMAKER_MOUNT_LOGS=False
DR_CLOUD_WATCH_ENABLE=False
DR_DOCKER_STYLE=swarm
DR_HOST_X=False
DR_WEBVIEWER_PORT=8100
# DR_DISPLAY=:99
# DR_REMOTE_MINIO_URL=http://mynas:9000
# CUDA_VISIBLE_DEVICES=0
```

`dr-upload-custom-files` finds this error message:
```
/deepracer-for-cloud$ dr-upload-custom-files
Uploading files to s3://bucketname/custom_files/
fatal error: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist

```

**Comment by RadioFront** [comment]
> `dr-upload-custom-files` finds this error message:
> 
> ```
> /deepracer-for-cloud$ dr-upload-custom-files
> Uploading files to s3://bucketname/custom_files/
> fatal error: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
> ```

Now added access key ID, and files can be uploaded with `dr-upload-custom-files`

```
~/deepracer-for-cloud$ dr-upload-custom-files
Uploading files to s3://bucket/custom_files/
upload: custom_files/model_metadata.json to s3://bucket/custom_files/model_metadata.json
upload: custom_files/reward_function.py to s3://bucket/custom_files/reward_function.py
upload: custom_files/hyperparameters.json to s3://bucket/custom_files/hyperparameters.json
```

**Comment by RadioFront** [comment]
Added AWS S3 real bucket hex string, and the boto error disappeared. Still Sagemaker is not running. Must be something else.

```
~/deepracer-for-cloud$ dr-start-training
Creating Robomaker configuration in s3://bucket/rl-deepracer-sagemaker/training_params.yaml
Updating service deepracer-0_rl_coach (id: 7critt5qo7s8gi8ofvopuevc7)
Updating service deepracer-0_robomaker (id: dw9el8fluhe2lwi1yidhn11ee)
Waiting up to 15 seconds for Sagemaker to start up...
Sagemaker is not running.
```

When repeated, `dr-start-training -w` started Sagemaker. Not sure what made it enabled. Will check what happens after reboot.
Also video stream is available, and it is cool.

**Comment by larsll** [comment]
@RadioFront - something went wrong in your configuration. If you have the type DR_CLOUD type `local` then normally you should also have:
DR_LOCAL_S3_BUCKET=bucket
DR_LOCAL_S3_PROFILE=minio

**Comment by RadioFront** [comment]
> @RadioFront - something went wrong in your configuration. If you have the type DR_CLOUD type `local` then normally you should also have: DR_LOCAL_S3_BUCKET=bucket DR_LOCAL_S3_PROFILE=minio

Thanks for your response. With your suggested set up, I can run the whole deepracer flow.
